### ISSUE TITLE
`abm_play` requires `abm_init_stepper_and_plot!` which is not in the latest version of `InteractiveDynamics.jl`

### ISSUE THREAD

**Issue by jarbus** [JuliaDynamics/InteractiveDynamics.jl#78] opened 2021-11-30 18:15 UTC
https://github.com/JuliaDynamics/InteractiveDynamics.jl/blob/25dac30087da07bbed6f96fc56b45e39d70f3207/src/agents/plots_videos.jl#L141

**Comment by fbanning** [comment] 2021-12-01 14:17
Sorry, this problem was caused by merging two divergent branches.

#79 fixes the problem and `abm_play` should work again once this is merged and you've updated your InteractiveDynamics installation. :)

**Comment by jarbus** [comment] 2021-12-01 15:12
Damn, this was fast. Thanks!!!

**Closed** 2021-12-01 15:44 UTC
Labels: bug
